from ubuntu

# install packages
run apt-get update && apt-get install -y \
    python3 \
    python3-pip


run pip3 install \
openai \
tensorflow \
keras \
matplotlib


run pip3 install \
sklearn


run pip3 install \
numpy

run pip3 install \
scikit-image

run pip3 install \
bs4

run echo "Europe/Berlin" > /etc/timezone

run DEBIAN_FRONTEND=noninteractive apt-get install -y \
tzdata

run dpkg-reconfigure -f noninteractive tzdata

run pip3 install \
pipreqs

run pip3 install \
ipython \
ipykernel

run pip3 install \
jupyter_client


# isntall module for soup

run pip3 install \
beautifulsoup4
